# Generated by Django 3.2 on 2022-04-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='volume',
            field=models.CharField(default='timezone.now', max_length=255),
            preserve_default=False,
        ),
    ]
